version: '3.8'

services:
  app:
    image: openjdk:11-jre-slim
    container_name: app
    ports:
      - "9999:9999"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./artifacts:/app
    command: java -jar /app/app-mbank.jar
    environment:
      DB_URL: jdbc:mysql://db:3306/app?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASS: root

  db:
    image: mysql:8.0
    container_name: app_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: